<a href="https://colab.research.google.com/github/Nasa19c/aipython/blob/main/2024_01_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
np.array([[1,2,3,4],[4,5,6,7]])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
arr1d = np.array(range(1,6))
print(arr1d)

[1 2 3 4 5]


In [9]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr2d.shape)
print(arr2d.ndim)
print(arr2d.dtype)

(2, 3)
2
int64


In [12]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr = np.arange(2,20,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [14]:
zeros_1d = np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


In [15]:
zeros_2d = np.zeros([3,4])
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
ones_1d = np.ones(5)
print(ones_1d)

[1. 1. 1. 1. 1.]


In [17]:
arr_1d = np.random.rand(5)
print(arr_1d)

[0.42555968 0.94977175 0.67538391 0.28246099 0.87352726]


In [24]:
arr_2d = np.random.rand(2,3)
print(arr_2d)

[[0.93406264 0.57837645 0.87256816]
 [0.21686821 0.76477143 0.38518943]]


In [25]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [27]:
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [29]:
arr2 = np.ones((3,4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
arr3 = np.linspace(0,1,10)
print(arr3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [37]:
A = np.arange(1,26)
A = A.reshape(5,5)

In [38]:
A.shape

(5, 5)

In [39]:
A[3][3]

19

In [62]:
A[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [66]:
A[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [69]:
A[:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [70]:
A[:,-2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [72]:
A = np.array(range(1,37)).reshape(3,3,4)
print(A)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [74]:
A.shape

(3, 3, 4)

In [75]:
A.size

36

In [81]:
A.reshape(3,4,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [78]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])